
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Deft.Component": "../../packages/deft/src/js/event/LiveEventBus.js",
  "Deft.InjectableComponent": "../../packages/deft/src/js/ioc/Injector.js",
  " Ext.Msg": "../../ext/src/window/MessageBox.js",
  "Ext": "../../ext/src",
  "Ext.rtl.EventObjectImpl": "../../ext/src/rtl/EventObject.js",
  "Phoenix": "../../app",
  "Deft": "../../packages/deft/src/js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Phoenix.context.ScenarioContext": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "Deft.event.LiveEventBus": [
    "Deft.LiveEventBus"
  ],
  "Phoenix.view.Notification": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Phoenix.view.ScenarioItemGrid": [],
  "Ext.ux.DataView.DragSelector": [],
  "Deft.mvc.Observer": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Phoenix.config.AppConfig": [],
  "Phoenix.view.MainPanel": [],
  "Deft.mvc.ViewController": [
    "Deft.ViewController"
  ],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Deft.promise.Resolver": [
    "Deft.Resolver"
  ],
  "Phoenix.store.ScenarioStore": [],
  "Deft.promise.Chain": [
    "Deft.Chain"
  ],
  "Phoenix.Application": [],
  "Ext.ux.PreviewPlugin": [],
  "Phoenix.store.AffectedItemStore": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [],
  "Phoenix.model.Probability": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Phoenix.service.ScenarioService": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "Deft.mixin.Controllable": [],
  "Phoenix.model.AffectedItem": [],
  "Ext.ux.event.Recorder": [],
  "Deft.event.LiveEventListener": [
    "Deft.LiveEventListener"
  ],
  "Ext.ux.ajax.SimManager": [],
  "Phoenix.store.ProbabilityStore": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Phoenix.model.Scenario": [],
  "Ext.ux.TabScrollerMenu": [],
  "Ext.ux.IFrame": [],
  "Deft.mvc.ComponentSelector": [],
  "Deft.ioc.DependencyProvider": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.TreePicker": [],
  "Deft.mvc.Application": [
    "Deft.Application"
  ],
  "Deft.promise.Deferred": [
    "Deft.Deferred"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "Ext.ux.BoxReorderer": [],
  "Deft.ioc.Injector": [
    "Deft.Injector"
  ],
  "Phoenix.view.ScenarioGrid": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [],
  "Phoenix.store.ScenarioItemStore": [],
  "Phoenix.controller.ScenarioGridController": [],
  "Deft.core.Class": [
    "Deft.Class"
  ],
  "Phoenix.view.Viewport": [],
  "Ext.ux.FieldReplicator": [],
  "Phoenix.context.AbstractContext": [],
  "Deft.mixin.Injectable": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Phoenix.controller.AbstractPhoenixController": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.GMapPanel": [],
  "Phoenix.store.RevenueImpactStore": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.GroupTabPanel": [],
  "Deft.util.Function": [
    "Deft.Function"
  ],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [],
  "Deft.InjectableComponent": [],
  "Phoenix.model.RevenueImpact": [],
  "Phoenix.service.NotificationService": [],
  "Ext.ux.DataView.Animated": [],
  "Deft.Component": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Deft.mvc.ComponentSelectorListener": [],
  "Phoenix.model.ScenarioItem": [],
  "Phoenix.view.ScenarioForm": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Player": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Phoenix.controller.ScenarioFormController": [],
  "Phoenix.controller.MainPanelController": [],
  "Ext.ux.DataView.Draggable": [],
  "Deft.log.Logger": [
    "Deft.Logger"
  ],
  "Ext.ux.TabCloseMenu": [],
  "Deft.promise.Promise": [
    "Deft.Promise"
  ],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": []
});
Ext.ClassManager.addNameAliasMappings({
  "Phoenix.context.ScenarioContext": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "Deft.event.LiveEventBus": [],
  "Phoenix.view.Notification": [
    "widget.uxNotification"
  ],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Phoenix.view.ScenarioItemGrid": [
    "widget.phoenix-view-scenarioItemGrid"
  ],
  "Ext.ux.DataView.DragSelector": [],
  "Deft.mvc.Observer": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Phoenix.config.AppConfig": [],
  "Phoenix.view.MainPanel": [
    "widget.phoenix-view-mainPanel"
  ],
  "Deft.mvc.ViewController": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Deft.promise.Resolver": [],
  "Phoenix.store.ScenarioStore": [],
  "Deft.promise.Chain": [],
  "Phoenix.Application": [],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Phoenix.store.AffectedItemStore": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Phoenix.model.Probability": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Phoenix.service.ScenarioService": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "Deft.mixin.Controllable": [],
  "Phoenix.model.AffectedItem": [],
  "Ext.ux.event.Recorder": [],
  "Deft.event.LiveEventListener": [],
  "Ext.ux.ajax.SimManager": [],
  "Phoenix.store.ProbabilityStore": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Phoenix.model.Scenario": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Deft.mvc.ComponentSelector": [],
  "Deft.ioc.DependencyProvider": [],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Deft.mvc.Application": [],
  "Deft.promise.Deferred": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "Ext.ux.BoxReorderer": [],
  "Deft.ioc.Injector": [],
  "Phoenix.view.ScenarioGrid": [
    "widget.phoenix-view-scenarioGrid"
  ],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Phoenix.store.ScenarioItemStore": [
    "store.scenarioItemStore"
  ],
  "Phoenix.controller.ScenarioGridController": [],
  "Deft.core.Class": [],
  "Phoenix.view.Viewport": [],
  "Ext.ux.FieldReplicator": [],
  "Phoenix.context.AbstractContext": [],
  "Deft.mixin.Injectable": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Phoenix.controller.AbstractPhoenixController": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Phoenix.store.RevenueImpactStore": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Deft.util.Function": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Deft.InjectableComponent": [],
  "Phoenix.model.RevenueImpact": [],
  "Phoenix.service.NotificationService": [],
  "Ext.ux.DataView.Animated": [],
  "Deft.Component": [],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Deft.mvc.ComponentSelectorListener": [],
  "Phoenix.model.ScenarioItem": [],
  "Phoenix.view.ScenarioForm": [
    "widget.phoenix-view-scenarioForm"
  ],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Player": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Phoenix.controller.ScenarioFormController": [],
  "Phoenix.controller.MainPanelController": [],
  "Ext.ux.DataView.Draggable": [],
  "Deft.log.Logger": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Deft.promise.Promise": [],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ]
});
