// Generated by CoffeeScript 1.4.0

window.executeJasmineSpecs = executeJasmineSpecs;

Ext.Loader.setConfig({
  enabled: true,
  paths: {
    "DeftTemplateGenerator": "../app",
    "DeftTemplateGenerator.test": "./js"
  }
});

Ext.application({
  autoCreateViewport: false,
  name: "DeftTemplateGenerator",
  appFolder: "../app",
  launch: function() {
    return window.Application = this;
  }
});

Ext.syncRequire(["DeftTemplateGenerator.test.JasmineApplication"]);

Ext.create("DeftTemplateGenerator.test.JasmineApplication");
