// Generated by CoffeeScript 1.4.0

describe("The Main Panel...", function() {
  var view, viewController;
  view = null;
  viewController = null;
  beforeEach(function() {
    createComponentTestArea();
    view = Ext.create("DeftTemplateGenerator.view.MainPanel", {
      renderTo: "componentTestArea"
    });
    return viewController = view.getController();
  });
  afterEach(function() {
    view.destroy();
    view = null;
    return viewController = null;
  });
  return describe("During a successful startup...", function() {
    return it("should create the main panel view and view controller", function() {
      expect(view != null).toBeBecause(true, "Main panel view should be defined.");
      expect(view.rendered).toBeBecause(true, "Main panel view should be rendered.");
      expect(view instanceof DeftTemplateGenerator.view.MainPanel).toBeBecause(true, "view should be an instance of MainPanel");
      expect(viewController != null).toBeBecause(true, "MainPanelController should be defined.");
      expect(viewController instanceof DeftTemplateGenerator.controller.MainPanelController).toBeBecause(true, "Main panel view should be an instance of MainPanelController.");
      return expect(viewController.getView() === view).toBeBecause(true, "View controller's getView() should return the MainPanel.");
    });
  });
});
