// Generated by CoffeeScript 1.4.0
/**
* Abstract ViewController for the Phoenix application.
*/

Ext.define("Phoenix.controller.AbstractPhoenixController", {
  extend: "Deft.mvc.ViewController",
  inject: ["scenarioContext", "scenarioService", "notificationService"],
  config: {
    scenarioContext: null,
    scenarioService: null,
    notificationService: null
  },
  init: function() {
    return this.callParent(arguments);
  }
});
