// Generated by CoffeeScript 1.4.0
/**
* Controls the main (root) UI container for the application.
*/

Ext.define("Phoenix.controller.MainPanelController", {
  extend: "Phoenix.controller.AbstractPhoenixController",
  requires: ["Phoenix.view.ScenarioForm"],
  observe: {
    scenarioContext: {
      scenarioOpened: "onScenarioOpened",
      scenarioDeleted: "onScenarioDeleted"
    }
  },
  control: {
    view: {
      boxready: "loadInitialData"
    }
  },
  init: function() {
    return this.callParent(arguments);
  },
  /**
  	* Loads the initial reference dta.
  */

  loadInitialData: function() {
    var _this = this;
    this.getView().setLoading(true);
    return this.getScenarioService().loadInitialData().then({
      success: function() {
        return _this.getScenarioContext().initialDataLoaded();
      },
      failure: function(errorMessage) {
        return _this.getNotificationService().error("Error", errorMessage);
      }
    }).always(function() {
      return _this.getView().setLoading(false);
    });
  },
  /**
  	* Responds when a {Phoenix.model.Scenario} view is opened.
  	* @param {Phoenix.model.Scenario} Scenario being opened.
  */

  onScenarioOpened: function(scenario) {
    var existingScenarioPanel;
    existingScenarioPanel = this.findExistingTab(scenario);
    if ((existingScenarioPanel != null)) {
      return existingScenarioPanel.show();
    } else {
      return this.getView().add({
        xtype: "phoenix-view-scenarioForm",
        itemId: "scenarioPanel_" + (scenario.getId()),
        title: scenario.get("name"),
        closable: true,
        scenario: scenario
      }).show();
    }
  },
  /**
  	* Responds when a {Phoenix.model.Scenario} is deleted.
  	* @param {Phoenix.model.Scenario} Scenario being deleted.
  */

  onScenarioDeleted: function(scenario) {
    var existingScenarioPanel;
    existingScenarioPanel = this.findExistingTab(scenario);
    if (existingScenarioPanel != null) {
      return existingScenarioPanel.close();
    }
  },
  /**
  	* Locates a view for the specified {Phoenix.model.Scenario}. If not view is open, returns null.
  	* @param {Phoenix.model.Scenario} Scenario to locate a view for.
  	* @return {Phoenix.view.ScenarioForm}
  */

  findExistingTab: function(scenario) {
    return this.getView().child("#scenarioPanel_" + (scenario.getId()));
  }
});
