// Generated by CoffeeScript 1.4.0

Ext.Loader.setConfig({
  enabled: true,
  paths: {
    "DeftTemplateGenerator": "js/app"
  }
});

Ext.syncRequire(["Ext.Component", "Ext.ComponentManager", "Ext.ComponentQuery"]);
