// Generated by CoffeeScript 1.4.0
/**
* Models the probability of a given disaster occurring.
*/

Ext.define("Phoenix.model.Probability", {
  extend: "Ext.data.Model",
  fields: [
    {
      name: "id"
    }, {
      name: "value",
      type: "string"
    }
  ]
});
