// Generated by CoffeeScript 1.4.0

describe("During initialization and setup, the application...", function() {
  it("should load ExtJS 4", function() {
    expect(Ext).toBeDefined();
    expect(Ext.getVersion() != null).toBeBecause(true, "Ext.getVersion() should return a value.");
    return expect(Ext.getVersion().major === 4).toBeBecause(true, "ExtJS major version is not 4.");
  });
  it("should load ExtJS application", function() {
    expect(window.Application != null).toBeBecause(true, "window.Application should be defined.");
    return expect(window.Application.name === "DeftTemplateGenerator").toBeBecause(true, "Application name should be DeftTemplateGenerator.");
  });
  it("should create DeftJS IoC items", function() {
    expect(Deft.ioc.Injector.canResolve("appConfig")).toBeBecause(true, "Injector should resolve appConfig.");
    return expect(Deft.ioc.Injector.canResolve("some_$unknown$_alias")).toBeBecause(false, "Injector should not resolve a dependency provider that doesn't exist.");
  });
  return it("should inject dependencies into a target object", function() {
    var target;
    target = {
      appConfig: null,
      someOtherProperty: null,
      config: {}
    };
    Deft.ioc.Injector.inject("appConfig", target);
    expect(target.appConfig != null).toBeBecause(true, "appConfig should be injected into target object.");
    return expect(target.someOtherProperty != null).toBeBecause(false, "A property with no dependency injected should remain null.");
  });
});
